/**
 * Status Transition Generator — DES-COD-006
 *
 * 仕様ファイルからステータス遷移を抽出し、TypeScript状態マシンクラス・Mermaid図を生成。
 */

export interface StatusDefinition {
  name: string;
  description: string;
  terminal?: boolean;
}

export interface TransitionRule {
  from: string;
  to: string;
  guard?: string;
  action?: string;
}

export interface StateMachineSpec {
  name: string;
  statuses: StatusDefinition[];
  transitions: TransitionRule[];
  initialStatus: string;
}

export class StatusTransitionGenerator {
  generate(spec: StateMachineSpec): string {
    const statusNames = spec.statuses.map((s) => `'${s.name}'`).join(' | ');
    const transitionEntries = spec.transitions
      .map((t) => {
        const guardStr = t.guard ? `, guard: '${t.guard}'` : '';
        const actionStr = t.action ? `, action: '${t.action}'` : '';
        return `    { from: '${t.from}', to: '${t.to}'${guardStr}${actionStr} }`;
      })
      .join(',\n');

    return [
      '/**',
      ` * State machine: ${spec.name}`,
      ' * Generated by StatusTransitionGenerator',
      ' */',
      '',
      `export type ${spec.name}Status = ${statusNames};`,
      '',
      `export class ${spec.name}StateMachine {`,
      `  private current: ${spec.name}Status;`,
      '',
      '  private readonly transitions = [',
      transitionEntries,
      '  ];',
      '',
      '  constructor() {',
      `    this.current = '${spec.initialStatus}';`,
      '  }',
      '',
      `  getStatus(): ${spec.name}Status {`,
      '    return this.current;',
      '  }',
      '',
      `  canTransition(to: ${spec.name}Status): boolean {`,
      '    return this.transitions.some(t => t.from === this.current && t.to === to);',
      '  }',
      '',
      `  transition(to: ${spec.name}Status): void {`,
      '    if (!this.canTransition(to)) {',
      '      throw new Error(`Cannot transition from ${this.current} to ${to}`);',
      '    }',
      '    this.current = to;',
      '  }',
      '}',
      '',
    ].join('\n');
  }

  toMermaid(spec: StateMachineSpec): string {
    const lines: string[] = ['stateDiagram-v2'];

    lines.push(`  [*] --> ${spec.initialStatus}`);

    for (const t of spec.transitions) {
      const label = t.guard ? ` : ${t.guard}` : '';
      lines.push(`  ${t.from} --> ${t.to}${label}`);
    }

    for (const s of spec.statuses) {
      if (s.terminal) {
        lines.push(`  ${s.name} --> [*]`);
      }
    }

    return lines.join('\n');
  }

  validate(spec: StateMachineSpec): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    const statusNames = new Set(spec.statuses.map((s) => s.name));

    if (!statusNames.has(spec.initialStatus)) {
      errors.push(`Initial status '${spec.initialStatus}' is not defined in statuses`);
    }

    for (const t of spec.transitions) {
      if (!statusNames.has(t.from)) {
        errors.push(`Transition references undefined status '${t.from}'`);
      }
      if (!statusNames.has(t.to)) {
        errors.push(`Transition references undefined status '${t.to}'`);
      }
    }

    // Detect unreachable states (not reachable from initial)
    const reachable = new Set<string>();
    const queue = [spec.initialStatus];
    while (queue.length > 0) {
      const current = queue.pop()!;
      if (reachable.has(current)) {
        continue;
      }
      reachable.add(current);
      for (const t of spec.transitions) {
        if (t.from === current && !reachable.has(t.to)) {
          queue.push(t.to);
        }
      }
    }

    for (const s of spec.statuses) {
      if (!reachable.has(s.name)) {
        errors.push(
          `Status '${s.name}' is unreachable from initial status '${spec.initialStatus}'`,
        );
      }
    }

    return { valid: errors.length === 0, errors };
  }
}

export function createStatusTransitionGenerator(): StatusTransitionGenerator {
  return new StatusTransitionGenerator();
}
